<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>false</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="Spectre.Console" Version="0.54.0" />
	</ItemGroup>

	<ItemGroup>
		<None Update="seeds_dataset_training.csv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="seeds_dataset_test.csv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="resultats.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>